[colors.primary]
background = '#111318'
foreground = '#e2e2e9'

[colors.selection]
text = '#e2e2e9'
background = '#2a4678'

[colors.cursor]
text = '#111318'
cursor = '#acc7ff'

[colors.normal]
black   = '#111318'
red     = '#e64c46'
green   = '#6fd66e'
yellow  = '#dbd27b'
blue    = '#5e80ce'
magenta = '#8d9dbf'
cyan    = '#acc7ff'
white   = '#abb2bf'

[colors.bright]
black   = '#5c6370'
red     = '#e0605f'
green   = '#87e086'
yellow  = '#e8e097'
blue    = '#b8d5ff'
magenta = '#507cac'
cyan    = '#6976b1'
white   = '#ffffff'
