preload = /home/zim/backgrounds/road.jpg
preload = /home/zim/backgrounds/pixel_art_dark_town.jpg
preload = /home/zim/backgrounds/embers_pixel_art.jpg
preload = /home/zim/backgrounds/dock.jpg
wallpaper = eDP-1,/home/zim/backgrounds/dock.jpg
