return {
  "nvim-treesitter/nvim-treesitter",
  branch = 'master',
  lazy = false,
  build = ":TSUpdate",
  config = function()
    local treesitter = require("nvim-treesitter.configs")
    treesitter.setup({
      ensure_installed = {
        "bash",
        "c",
        "c_sharp",
        "cpp",
        "css",
        "csv",
        "fish",
        "git_config",
        "git_rebase",
        "gitattributes",
        "gitcommit",
        "gitignore",
        "go",
        "gpg",
        "html",
        "javascript",
        "json",
        "json5",
        "latex",
        "lua",
        "luadoc",
        "markdown",
        "markdown_inline",
        "nix",
        "nu",
        "powershell",
        "python",
        "qmljs",
        "razor",
        "regex",
        "rust",
        "sql",
        "svelte",
        "toml",
        "tsx",
        "typescript",
        "typst",
        "vim",
        "vimdoc",
        "xml",
        "yaml",
        "zig",
        "ziggy",
        "ziggy_schema"
      },
      highlight = { enable = true },
    })
  end
}
