theme = "catppuccin_mocha"

[editor]
line-number = "relative" # DEFAULT
mouse = false
cursorline = true # DEFAULT
color-modes = true # colors for modes in statusline
rulers = [80, 120]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true
character = "▏"

[editor.whitespace]
render = "all"

[editor.auto-pairs]
'<' = '>'
'[' = ']'
'(' = ')'
'{' = '}'
'`' = '`'

[editor.statusline]
separator = "|"

[keys.normal]
c = "change_selection_noyank"
D = ["collapse_selection", "select_mode", "goto_line_end", "delete_selection"]
C = ["collapse_selection", "select_mode", "goto_line_end", "delete_selection", "insert_mode"]
o = ["add_newline_below", "move_line_down"]
O = ["add_newline_above", "move_line_up"]
m = { t = ["switch_case"], l = ["switch_to_lowercase"], u = ["switch_to_uppercase"] }
Z = { Z = ":wq", Q = ":q!"}
backspace = "collapse_selection"
esc = "collapse_selection"
# tab = "repeat_last_motion"
X = "extend_line_above"
C-q = "wclose"
A-x = "extend_to_line_bounds"
space = { c = ":buffer-close!", space = ":write", C = [":write", ":buffer-close"], q = ":buffer-close-others" }
minus = ["copy_selection_on_prev_line"]
"+" = ["copy_selection_on_next_line"]
"(" = ["goto_previous_buffer"]
")" = ["goto_next_buffer"]
"H" = ["rotate_selections_backward"]
"L" = ["rotate_selections_forward"]
"{" = ["goto_prev_paragraph"]
"}" = ["goto_next_paragraph"]

[keys.select]
X = "extend_line_above"

# TODO: Use `_` for something better. `space t` for trim