[[language]]
name = "markdown"
language-server = { command = "ltex-ls" }
formatter = { command = 'prettier', args = ["--parser", "markdown" ] }
auto-format = true
file-types = ["md", "org", "tex"]
scope = "source.markdown"
roots = []  

# [[language]]
# name = "markdown"
# scope = "source.md"
# injection-regex = "md|markdown"
# formatter = { command = 'prettier', args = ["--parser", "markdown" ] }
# auto-format = true
# file-types = ["md"]
# roots = [".marksman.toml"]
# language-server = { command = "marksman", args=["server"] }
# indent = { tab-width = 2, unit = "  " }