[[language]]
auto-format = true
name = "rust"

[[language]]
language-servers = ["vscode-html-language-server", "tailwindcss-ls"]
name = "html"

[[language]]
language-servers = ["vscode-css-language-server", "tailwindcss-ls"]
name = "css"

[[language]]
language-servers = ["typescript-language-server", "tailwindcss-ls"]
name = "jsx"

[[language]]
language-servers = ["typescript-language-server", "tailwindcss-ls"]
name = "tsx"

[[language]]
language-servers = ["svelteserver", "tailwindcss-ls"]
name = "svelte"

[language-server.rust-analyzer.config.check]
command = "clippy"
